<!-- 
	Control Panel HTML code
	Written by Luiza Silva
	Last updated: 18/11/10

	Requires: Blueprint framework
		  Proper CSS (in template.css)

	A note: this initially was a php class, but
	since it is mostly static, it was transformed
	into this include file.
-->

<div id="cpWrapper" class="span-22 prepend-1 append-1 last">
	<div class="span-3 append-4 prepend-17 last">
		<div id="cpTag" class="span-3 last center">
			<p>Edit me!</p>
		</div>
	</div>
	<div id="cpPanel" class="span-22 last">
		<div id="cpGlobalEdit" class="span-16">
			<div class="cpButton span-3 center">Menu</div>
			<div class="cpButton span-3 center">Site Info</div>
			<div class="cpButton span-3 center">Photos</div>
			<div class="cpButton span-3 center">Videos</div>
			<div class="cpButton span-3 center">Gallery</div>
		</div>
		<div id="cpLocalEdit" class="span-4 last prepend-1 append-1">
			<div class="cpButton span-4 center last">Edit this page!</div>
		</div>
	</div>
</div>

<!-- End of control panel HTML code -->

