
<!--
PHP template for TrabBD
Last updated: 05/11/10 by Luiza
-->

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<!-- Charset declaration -->
		<meta http-equiv="Content-type" content="text/html; charset=UTF-8" />			

		<!-- Including blueprint framework (in the layout folder) -->
		<link rel="stylesheet" type="text/css" href="layout/blueprint/screen.css" media="screen, projection" />
		<link rel="stylesheet" type="text/css" href="layout/blueprint/print.css" media="print" />
		<!--[if lt IE 8]><link rel="stylesheet" type="text/css" href="layout/blueprint/ie.css" media="screen, projection" /><![endif]-->

		<!-- Including our CSS-->
		<link rel="stylesheet" type="text/css" href="layout/template.css" media="screen" />

		<title>##TITLE_GOES_HERE##</title>		
	</head>

	<body>
		<div class="container showgrid">
			<div class="span-24" id="header">  
				##HEADER_GOES_HERE##
			</div>  
			<div class="span-24" id="menu">  
				##MENU_GOES_HERE##
			</div>  
			<div class="span-24" id="main">  
				##MAIN_CONTENT_GOES_HERE##
			</div>  
		</div>
	</body>
</html>

